# -*- coding: utf-8 -*-
"""TF-G4-Analysis.ipynb

Automatically generated by Colaboratory.

# Trabajo Final - Palabras de soporte complementarias a la calificación de un restaurant
## Grupo 4

### Importación de datasets originados por scrapping
"""
